### ISSUE TITLE
function of set_layer_with_name_and_path

### ISSUE THREAD

**Issue by yj373** [wooyeolBaek/attention-map#7]
Hello!

Thank you for your awesome work! I am trying to understand your code. For the method ```def set_layer_with_name_and_path```, I am wondering what the main function of this method is. It seems like you are trying to update the forward function of each target module into the customized forward function in ```module.py```. My questions are as follows:
1. Is my understanding correct?
2. What do ```current_path``` and ```new_path``` mean here? And why do you keep track of them?

I would really appreciate it if you could help me understand your code. Thank you so much!

**Comment by wooyeolBaek** [comment]
@yj373 
Yes, that’s correct. The `current_path` and `new_path` were from an older version, and it looks like they weren’t removed when I updated the code. They’re unnecessary now, so you can just ignore them. Thanks for pointing that out, by the way.
